export const SEMESTERS_COUNTED = ["spring", "summer", "fall"];

export const DEPARTMENTS = [
  "Architecture",
  "Art",
  "Arts & Entertainment Management",
  "BXA Intercollege Degree Programs",
  "Biological Sciences",
  "Biomedical Engineering",
  "Business Administration",
  "CFA Interdisciplinary",
  "CIT Interdisciplinary",
  "Carnegie Mellon University-Wide Studies",
  "Center for the Arts in Society",
  "Chemical Engineering",
  "Civil & Environmental Engineering",
  "Computational Biology",
  "Computer Science",
  "Computer Science and Arts",
  "Design",
  "Dietrich College Information Systems",
  "Dietrich College Interdisciplinary",
  "Drama",
  "Economics",
  "Electrical & Computer Engineering",
  "Engineering & Public Policy",
  "English",
  "Entertainment Technology Pittsburgh",
  "General Dietrich College",
  "Heinz College Wide Courses",
  "History",
  "Human-Computer Interaction",
  "Humanities and Arts",
  "Information & Communication Technology",
  "Information Networking Institute",
  "Information Systems:Sch of IS & Mgt",
  "Institute of Politics and Strategy",
  "Institute for Software Research",
  "Integrated Innovation Institute",
  "Language Technologies Institute",
  "MCS Interdisciplinary",
  "Machine Learning",
  "Materials Science & Engineering",
  "Mathematical Sciences",
  "Mechanical Engineering",
  "Medical Management:Sch of Pub Pol & Mgt",
  "Modern Languages",
  "Music",
  "Naval Science - ROTC",
  "Neuroscience Institute",
  "Philosophy",
  "Physical Education",
  "Physics",
  "Psychology",
  "Public Management:Sch of Pub Pol & Mgt",
  "Public Policy & Mgt:Sch of Pub Pol & Mgt",
  "Robotics",
  "SCS Interdisciplinary",
  "Science and Arts",
  "Social & Decision Sciences",
  "Statistics and Data Science",
  "StuCo (Student Led Courses)",
];